baseURL: 'https://example.com'
title: Ollie Fox
paginate: 5
theme: oso

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: dev
          url: /tags/development
          weight: 5
        - name: music
          url: /tags/music
          weight: 10

paginate: 20

params:
  env: production

  # Available themes: gotham, toothpaste, dracula, gandalf, red-graphite
  colorTheme: gotham

  # Font family: IBM Plex, available styles: serif, sans
  fontStyle: sans 

  # Plausible.io is an open-source alternative to Google Analytics
  plausible: true

  postProgress: true

  homePage:
    title: Ollie Fox
    description: Welcome to my blog!
    author: Ollie Fox
    pronouns: they/them
    avatar: memoji.png

    # Look in docs/icons.md for a full list of available social icons
    socialIcons:
    - name: github
      url: 'https://github.com/username'
    - name: dribbble
      url: 'https://dribbble.com/username'
    - name: twitter
      url: 'https://twitter.com/username'

  assets:
    favicon: '/favicon.ico'
