# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "oso"
license = "MIT"
licenselink = "https://github.com/raulcodes/oso/blob/master/LICENSE"
description = "A simple Hugo theme inspired by the popular iOS note-taking app, Bear."
homepage = "https://github.com/raulcodes/oso"
tags = ["Responsive", "Simple", "Clean", "Light", "White", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.1.0"

[author]
  name = "raulcodes"
  homepage = "https://raulcodes.com/"

# If porting an existing theme
[original]
  name = "Paper"
  author = "nanxiaobei"
  homepage = "https://github.com/nanxiaobei"
  repo = "https://github.com/nanxiaobei/hugo-paper/"
